JazzywebdoDocBundle:
    resource: "@JazzywebdoDocBundle/Resources/config/routing.yml"
    prefix:   /

JMDServerBundle:
    resource: "@JMDServerBundle/Resources/config/routing.yml"	
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin