books_crud:
    pattern:  /
    defaults: { _controller: "JazzywebdoDocBundle:Book:index" }

books_crud_show:
    pattern:  /{id}/show
    defaults: { _controller: "JazzywebdoDocBundle:Book:show" }

books_crud_new:
    pattern:  /new
    defaults: { _controller: "JazzywebdoDocBundle:Book:new" }

books_crud_create:
    pattern:  /create
    defaults: { _controller: "JazzywebdoDocBundle:Book:create" }
    requirements: { _method: post }

books_crud_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "JazzywebdoDocBundle:Book:edit" }

books_crud_update:
    pattern:  /{id}/update
    defaults: { _controller: "JazzywebdoDocBundle:Book:update" }
    requirements: { _method: post }

books_crud_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "JazzywebdoDocBundle:Book:delete" }
    requirements: { _method: post }
