JazzywebdoDocBundle_api_rest_get_collection:
   pattern:  /book/{book}/docs
   defaults: { _controller: JazzywebdoDocBundle:APIRest:getAllDocuments }
   requirements:
     _method: GET
     _format: json

JazzywebdoDocBundle_api_rest_get_doc:
   pattern: /book/{book}/docs/{docname}
   defaults: { _controller: JazzywebdoDocBundle:APIRest:getDocument }
   requirements:
     _method: GET
     _format: json
    
JazzywebdoDocBundle_api_rest_post_doc:
   pattern: /book/{book}/docs/{docname}
   defaults: { _controller: JazzywebdoDocBundle:APIRest:createOrSaveDocument }
   requirements:
     _method: POST
     _format: json
    
JazzywebdoDocBundle_api_rest_put_doc:
   pattern: /book/{book}/docs/{docname}
   defaults: { _controller: JazzywebdoDocBundle:APIRest:createOrSaveDocument }
   requirements:
     _method: PUT
     _format: json

JazzywebdoDocBundle_api_rest_delete_doc:
   pattern: /book/{book}/docs/{docname}
   defaults: { _controller: JazzywebdoDocBundle:APIRest:removeDocument }
   requirements:
     _method: DELETE
     _format: json

JazzywebdoDocBundle_guiapp_editor:
  pattern: /editor/{book}
  defaults: { _controller: JazzywebdoDocBundle:GUIApp:editor }
  requirements:
     _method: GET

JazzywebdoDocBundle_guiapp_upload_tool:
  pattern: /uploadtool/ui/{book}
  defaults: { _controller: JazzywebdoDocBundle:Upload:uploadTool }
  requirements:
     _method: GET
     
JazzywebdoDocBundle_guiapp_api_upload_getallfiles:
  pattern: /uploadtool/book/{book}
  defaults: { _controller: JazzywebdoDocBundle:Upload:getAll }
  requirements:
     _method: GET
     
JazzywebdoDocBundle_guiapp_api_upload_getfile:
  pattern: /uploadtool/book/{book}/{file}
  defaults: { _controller: JazzywebdoDocBundle:Upload:get }
  requirements:
     _method: GET

JazzywebdoDocBundle_guiapp_api_upload_delete:
  pattern: /uploadtool/book/{book}/{file}
  defaults: { _controller: JazzywebdoDocBundle:Upload:delete }
  requirements:
     _method: DELETE


JazzywebdoDocBundle_guiapp_api_upload_post:
  pattern: /uploadtool/book/{book}
  defaults: { _controller: JazzywebdoDocBundle:Upload:post }
  requirements:
     _method: POST
