JazzywebdoDocBundle_api_rest_get_collection:
   pattern:  /book/{book}/docs
   defaults: { _controller: JazzywebdoDocBundle:APIRest:getAllDocuments }
   requirements:
     _method: GET
     _format: json

JazzywebdoDocBundle_api_rest_get_doc:
   pattern: /book/{book}/docs/{docname}
   defaults: { _controller: JazzywebdoDocBundle:APIRest:getDocument }
   requirements:
     _method: GET
     _format: json
    
JazzywebdoDocBundle_api_rest_post_doc:
   pattern: /book/{book}/docs/{docname}
   defaults: { _controller: JazzywebdoDocBundle:APIRest:createOrSaveDocument }
   requirements:
     _method: POST
     _format: json
    
JazzywebdoDocBundle_api_rest_put_doc:
   pattern: /book/{book}/docs/{docname}
   defaults: { _controller: JazzywebdoDocBundle:APIRest:createOrSaveDocument }
   requirements:
     _method: PUT
     _format: json

JazzywebdoDocBundle_api_rest_delete_doc:
   pattern: /book/{book}/docs/{docname}
   defaults: { _controller: JazzywebdoDocBundle:APIRest:removeDocument }
   requirements:
     _method: DELETE
     _format: json

JazzywebdoDocBundle_guiapp_editor:
  pattern: /editor/{book}
  defaults: { _controller: JazzywebdoDocBundle:GUIApp:editor }
  requirements:
     _method: GET
     
     
JazzywebdoDocBundle_api_upload_getallfiles:
  pattern: /uploadtool/dir/{dir}
  defaults: { _controller: JazzywebdoDocBundle:Upload:getAll }
  requirements:
     _method: GET

JazzywebdoDocBundle_api_upload_images_getallfiles:
  pattern: /uploadtool/images/{dir}
  defaults: { _controller: JazzywebdoDocBundle:Upload:getAll }
  requirements:
     _method: GET

JazzywebdoDocBundle_api_upload_getfile:
  pattern: /uploadtool/dir/{dir}/{file}
  defaults: { _controller: JazzywebdoDocBundle:Upload:get }
  requirements:
     _method: GET

JazzywebdoDocBundle_api_upload_images_getfile:
  pattern: /uploadtool/images/{dir}/{file}
  defaults: { _controller: JazzywebdoDocBundle:Upload:get }
  requirements:
     _method: GET

JazzywebdoDocBundle_api_upload_delete:
  pattern: /uploadtool/dir/{dir}/{file}
  defaults: { _controller: JazzywebdoDocBundle:Upload:delete }
  requirements:
     _method: DELETE

JazzywebdoDocBundle_api_upload_images_delete:
  pattern: /uploadtool/images/{dir}/{file}
  defaults: { _controller: JazzywebdoDocBundle:Upload:delete }
  requirements:
     _method: DELETE

JazzywebdoDocBundle_api_upload_post:
  pattern: /uploadtool/dir/{dir}
  defaults: { _controller: JazzywebdoDocBundle:Upload:post }
  requirements:
     _method: POST

JazzywebdoDocBundle_api_upload_images_post:
  pattern: /uploadtool/images/{dir}
  defaults: { _controller: JazzywebdoDocBundle:Upload:post }
  requirements:
     _method: POST

JazzywebdoDocBundle_guiapp_upload_tool:
  pattern: /uploadtool/gui/{book}
  defaults: { _controller: JazzywebdoDocBundle:GUIApp:uploadTool}
  requirements:
     _method: GET
     
JazzywebdoDocBundle_guiapp_upload_images_tool:
  pattern: /uploadtool/gui/images/{book}
  defaults: { _controller: JazzywebdoDocBundle:GUIApp:uploadTool, images: true}
  requirements:
     _method: GET