parameters:
    jazzyweb.dodocmanager.class: Jazzyweb\doDocBundle\Services\docManager
    jazzyweb.dodocmanager.docdir: /Users/juanda/Sites/easybook/docs
    jazzyweb.dodocmanager.contentsdirname: Contents
    jazzyweb.dodocmanager.outputdirname: Output
    jazzyweb.dodocmanager.configfilename: config.yml
    
    jazzyweb.dodocuploadhandler.class: Jazzyweb\doDocBundle\Services\docUploadHandler
    jazzyweb.dodocuploadhandler.url_api: /uploadtool
    jazzyweb.dodocuploadhandler.thumbnail_reldir: thumbnail
    
    jazzyweb.dodoceasybookbridge.class: Jazzyweb\doDocBundle\Services\EasyBookBridge
    

services:
    jazzyweb.dodocmanager:
        class: %jazzyweb.dodocmanager.class%
        arguments:
         - "@doctrine"  
         - %jazzyweb.dodocmanager.docdir%
         - %jazzyweb.dodocmanager.contentsdirname%
         - %jazzyweb.dodocmanager.outputdirname%
         - %jazzyweb.dodocmanager.configfilename%
   
    jazzyweb.dodocuploadhandler:
       scope: request
       class: %jazzyweb.dodocuploadhandler.class%
       arguments:
         - "@request"
         - "@jazzyweb.dodocmanager"      
         - %jazzyweb.dodocuploadhandler.url_api%
         - %jazzyweb.dodocuploadhandler.thumbnail_reldir%
    
    jazzyweb.dodoceasybookbridge:       
       class: %jazzyweb.dodoceasybookbridge.class%
       arguments:
         - "@jazzyweb.dodocmanager"

  
    sonata.dodoc.admin.book:
       class: Jazzyweb\doDocBundle\Admin\BookAdmin
       tags:
          - { name: sonata.admin, manager_type: orm, group: 'Administration', label: Books }
       arguments:
          - null
          - Jazzyweb\doDocBundle\Entity\Book
          - JazzywebdoDocBundle:Admin
          - "@jazzyweb.dodoceasybookbridge"