parameters:
    jazzyweb.dodocmanager.class: Jazzyweb\doDocBundle\Services\docManager
    jazzyweb.dodocmanager.docdir: /Users/juanda/Sites/doDoc/web/docs
    jazzyweb.dodocmanager.contentsdirname: Contents
    jazzyweb.dodocmanager.outputdirname: Output
    jazzyweb.dodocmanager.configfilename: config.yml
    
    jazzyweb.dodocuploadhandler.class: Jazzyweb\doDocBundle\Services\docUploadHandler
    jazzyweb.dodocuploadhandler.url_api: /uploadtool/book/
    

services:
    jazzyweb.dodocmanager:
        class: %jazzyweb.dodocmanager.class%
        arguments:
         - "@doctrine"  
         - %jazzyweb.dodocmanager.docdir%
         - %jazzyweb.dodocmanager.contentsdirname%
         - %jazzyweb.dodocmanager.outputdirname%
         - %jazzyweb.dodocmanager.configfilename%
   
    jazzyweb.dodocuploadhandler:
       class: %jazzyweb.dodocuploadhandler.class%
       arguments:
         - "@jazzyweb.dodocmanager"
         - %jazzyweb.dodocuploadhandler.url_api%