parameters:
    jazzyweb.dodocmanager.class: Jazzyweb\doDocBundle\Services\docManager
    jazzyweb.dodocmanager.docdir: /Users/juanda/Sites/easybook/docs
    jazzyweb.dodocmanager.contentsdirname: Contents
    jazzyweb.dodocmanager.outputdirname: Output
    jazzyweb.dodocmanager.configfilename: config.yml
    
    jazzyweb.dodocuploadhandler.class: Jazzyweb\doDocBundle\Services\docUploadHandler
    jazzyweb.dodocuploadhandler.url_api: /uploadtool/book
    jazzyweb.dodocuploadhandler.thumbnail_reldir: thumbnail
    

services:
    jazzyweb.dodocmanager:
        class: %jazzyweb.dodocmanager.class%
        arguments:
         - "@doctrine"  
         - %jazzyweb.dodocmanager.docdir%
         - %jazzyweb.dodocmanager.contentsdirname%
         - %jazzyweb.dodocmanager.outputdirname%
         - %jazzyweb.dodocmanager.configfilename%
   
    jazzyweb.dodocuploadhandler:
       scope: request
       class: %jazzyweb.dodocuploadhandler.class%
       arguments:
         - "@request"
         - "@jazzyweb.dodocmanager"      
         - %jazzyweb.dodocuploadhandler.url_api%
         - %jazzyweb.dodocuploadhandler.thumbnail_reldir%