parameters:
   jmd_server.markdown.class: Jazzyweb\MarkDownServerBundle\Services\Markdown2Html

services:
    jmd_server.markdown.service:
         class: %jmd_server.markdown.class%
#        arguments: [@service_id, "plain_value", %parameter%]
